### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by cwfoo** [erlport/erlport#8]
How do I install erlport?

The README links to http://erlport.org, which shows installation instructions for a version of erlport that is no longer maintained (i.e. [hdima/erlport](https://github.com/hdima/erlport)).

On PyPi, the [erlport](https://pypi.org/project/erlport/) listed is for [hdima/erlport](https://github.com/hdima/erlport), not this erlport.

What about the [erlport](https://hex.pm/packages/erlport) listed on https://hex.pm? Is that the abandoned erlport, or is it this one? hex.pm lists version 0.10.0 (16 Aug 2018) and version 0.9.8 (20 Dec 2016), but this repository shows no such releases. The abandoned erlport has no such releases either (its latest releases are `1.0.0alpha` [10 Jun 2013] and `v0.7` [23 Apr 2013]).

So how do I install this erlport?

**Comment by filmor** [comment]
The current state is that this repository was started as an attempt to keep erlport on life-support. Its master has all important PRs from the original (abandoned) repository merged.

I don't have access to the Hex feed, the owners are @feng19 and @jeffutter, wo are also co-owners of the `erlport` organisation here. Nothing has been published from this repository to `pypi` yet.

You can use this version (as long as the Hex package is not published from here) by referring to it explicitly from rebar3 via the repository path.

**Comment by feng19** [comment]
Holle! @filmor, I'm so sorry for I didn't have more time to take part in maintenance on this project. I already added your account to the [erlport](https://hex.pm/packages/erlport) owner list. Thanks for your participation.

**Comment by filmor** [comment]
Thanks. The version 0.10.1 is the first one published from this fork and further releases to Hex will come from here as well.
